### PR TITLE
Simple Dockerfile to use the server in a Dockercontainer

### PR DESCRIPTION
**Pull request by deluxe2**
Wanted to run the server into a Dockercontainer. So i made this and thought i should share it with everyone who wants to do the same.

Added Dockerfile and some basic Documentation.

Changed the directories for some config files to allow docker to mount a single config directory with all the files which my be edited.
Probably needs a migrationfeature for the moved files. 

If you have improvements name them so i can make this better. Also if you dont want to merge this please send a short response and close this issue.

### CODE REVIEW

**Comment by RockyTV** [comment]
Why not mount the whole server folder instead of mounting separate folders?

**Comment by deluxe2** [comment]
I tried to to only mount folder wich should be persistant and/or need to be modified by the User. So if you update the server build a new Container run it with the same volume or mount and everything is up and running. You don't need to worry about the binaries. Everything you don't need to edit is hidden inside the container. 

Desired way to update:

```bash
git pull
docker build -t dmp-server:[version] .
docker run docker run -d \
  -p 6702:6702 \
  -v [path/on/host]:/DMP/Config \
  -v dmpsave:/DMP/Universe \
  dmp-server:[version]
```
I hope this makes my intentions clear. I'm not used to write such things in english. If questions arise just ask.

**Comment by RockyTV** [comment]
Okay. What about the other ports that should be exposed, like the JSON status page? Or the RCON (#444) protocol?

**Comment by deluxe2** [comment]
If it's okay and you don't want to merge the changes I made. I would like to make containers and share them on dockerhub. Everytime you release a new version I would make a new image. Also improve the documentation to match more use cases and provide support if needed.

**Comment by RockyTV** [comment]
It's possible to setup a deploy script to automatically build new images when a new version is released. I'll take a look at it.

**Comment by RockyTV** [comment]
I've slightly changed your commit, but maintained you as the author. The server files are in `/server/` and the previous commit moved any config file to `Config/`, making it accessible via `/server/Config/`. I'll add a small documentation for the Docker image and will try setting up automatic builds.

Thank you!

**Pull request closed without merging**
