### PR TITLE
Ported to SettingsParser library

### PR DESCRIPTION
**Pull request by RockyTV**

### CODE REVIEW

**Comment by oldmud0** [comment]
Okay. Sure. Where's this SettingsParser though?

**Comment by RockyTV** [comment]
@oldmud0 http://github.com/rockytv/settingsparser

**Comment by oldmud0** [comment]
Okay, looks pretty straightforward. Is this going to be imported via a submodule?

**Comment by RockyTV** [comment]
Closed, implemented via ac5a258.

**Pull request closed without merging**
