### PR TITLE
Add nukeall command to remove all vessels from universe

### PR DESCRIPTION
**Pull request by dsonbill**
This should be fine. It's untested, but I copied all of it from NukeKSC and just modified it a bit.

### CODE REVIEW

**Comment by oldmud0** [comment]
This may have terrible consequences if the vessels are being controlled. Will players be kicked out to the space center right before their vessels are destroyed?

**Comment by dsonbill** [comment]
@oldmud0 - Remember, this works the same way as NukeKSC, so if that doesn't have consequences, neither will this.

**Comment by oldmud0** [comment]
What about emotional consequences?

**Comment by dsonbill** [comment]
That's up to server admins to deal with, lol.

**Comment by godarklight** [comment]
Don't really need this ;)

**Pull request closed without merging**
