### PR TITLE
Re-generate mod data file when server starts

### PR DESCRIPTION
**Pull request by RockyTV**

### CODE REVIEW

**Comment by oldmud0** [comment]
Why can't we have a "vanilla parts" file that is automatically generated (`"do not edit this file"`) and another for modded parts (not automatically generated)?

**Comment by godarklight** [comment]
As is, this is currently a bad idea - all servers would reset back to vanilla on boot

oldmud0's idea isn't a bad one, but I might have to ask server admins what they think of it :)

**Comment by RockyTV** [comment]
Well, it's still better than having servers with banned stock parts.

**Comment by RockyTV** [comment]
I'm giving it a go.

**Pull request closed without merging**
