### PR TITLE
Fixed docker image and sourcified the repo

### PR DESCRIPTION
**Pull request by Cyclic3**
The docker image was non-functional, and there appeared to be 2 DLLs in the git repo. I found the source of these DLLs and added them as submodules, and tied them into the project as references.

The docker image doesn't work on my machine, and is hardwired to the existing DLLs. I have modified it a bit to work with the new system, as well as fixing the failure to build bug I had before.

I have run `docker build .` on this repo and got a binary that appears to run fine. I am yet to test it in game.

### CODE REVIEW

**Comment by RockyTV** [comment]
Sorry for only getting to this now, but are you sure? It worked for me in my Linux machine (in fact I wrote the Dockerfile in it).

**Comment by Cyclic3** [comment]
@RockyTV Here are my logs:
```
Sending build context to Docker daemon  4.112MB
Step 1/10 : FROM mono:latest
 ---> 43b7ab8e1f34
Step 2/10 : COPY ./Common /build/Common
 ---> 7653392b9274
Step 3/10 : COPY ./Server /build/Server
 ---> fbdb361fb8f7
Step 4/10 : COPY ./SettingsParser.dll /build/
 ---> 163a85b6b938
Step 5/10 : COPY ./MessageWriter2 /build/
COPY failed: stat /var/lib/docker/tmp/docker-builder029342981/MessageWriter2: no such file or directory
```

I can fix this by adding a `.dll` to the end of the first argument of the copy command.

However, this merge also removes the dlls from the repo and replaces them with submodules, which allows the repo to be built fully from source, as well as easing updates of dependencies.

Please feel free to cherry-pick from my commit if the second change is unwanted!

**Comment by Cyclic3** [comment]
I would also like to add that I have used this patched version on my own kuberentes cluster, and it has worked like a charm

**Comment by RockyTV** [comment]
I have fixed the Dockerfile. Could you give it a try?

Sorry for taking too long to look at it, turns out there was a typo in the `MessageWriter2.dll` file, so it wasn't copied to the build directory. I've also included the new `UDPMeshLib.dll` file that was added in v0.3.0.0.

We don't need to retrieve these DLLs from source because they are already provided in the repository.

**Comment by Cyclic3** [comment]
@RockyTV Personally I try to keep as few binaries in my source tree as possible. If we are keeping open source binaries in the tree, would it be worth maybe adding a link to them in the readme for interested users?

**Pull request closed without merging**
